language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      sudo: false
      osx_image: xcode8.3

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - rpm
      - graphviz
      

install:
  - npm install

script:
  - npm run dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"