db:
  url: 'jdbc:oracle:thin:@192.168.0.55:8080:ARKHI'
  driver: oracle.jdbc.OracleDriver
  username: Master
  password: arkhi
  datasource:
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 1
    max-wait: 20000
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 30
    abandon-when-percentage-full: 50
    jdbcInterceptors: ResetAbandonedTimer
logging:
  level:
    com.arterh.esocial: INFO
    com.arkhi.esocial.util: INFO
    org.apache.activemq: FATAL
watchdog:
  frequencia:
    db: '*/30 * * * * *'
    mensageria: '*/30 * * * * *'
    esocial: '*/30 * * * * *'
    serpro: '*/30 * * * * *'
esocial:
  leitor.endereco: 'http://localhost:5555/healthcheck'
  integrador.endereco: 'http://localhost:5556/healthcheck'
  mensagens.endereco: 'http://localhost:8161/'
  serpro:
    producao:
      envio: >-
        https://webservices.envio.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc
      consulta: >-
        https://webservices.consulta.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc
    pre_producao:
      envio: >-
        https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc
      consulta: >-
        https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc
  http_timeout: 1000
spring:
  output:
    ansi:
      enabled: always
