spring:
  activemq:
    broker-url: >-
      failover://(tcp://localhost:61616,tcp://localhost:61617)?persistent=true&schedulerSupport=true&useExponentialBackOff=true&warnAfterReconnectAttempts=5
    user: admin
    password: admin
    in-memory: false
db:
  url: 'jdbc:sqlserver://192.168.0.1:6060;databaseName=ARKHI'
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  username: SQL SERVER
  password: '1234'
  datasource:
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 1
    max-wait: 20000
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 30
    abandon-when-percentage-full: 50
    jdbcInterceptors: ResetAbandonedTimer
logging:
  level:
    com.arterh.esocial: DEBUG
    com.arkhi.esocial.util: DEBUG
    org.apache.activemq: WARN
  file: esocial.log
certificado:
  servidor:
    chave: >-
      C:\Users\Lenovo\Documents\Estudos
      Electron\CopiaElectron_YAML_TESTE\readme.md
    senha: GeF6/aEOfyRar6DPW641Yg==
serpro:
  url_producao:
    envio: >-
      https://webservices.envio.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc
    consulta: >-
      https://webservices.consulta.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc
  url_pre_producao:
    envio: >-
      https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc
    consulta: >-
      https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc
esocial:
  evento:
    naoprocessado: L
    extraidoparaenvio: X
    recebidopelogoverno: R
    extraidoparaconsulta: C
  tamanhoMaximoPacote: 750
  maximoEventosPorPacote: 50
  empregadores:
    - codigo: '10251900'
      chave: 'C:\Users\Lenovo\Downloads\apache-activemq-5.15.3-bin.zip'
      senha: fmVAlXiEcsx8Mh+YcAeDnA==
      tipo-transmissor: '2'
      numero-transmissor: '10251900681'
    - codigo: '11111111'
      chave: 'C:\Users\Lenovo\Desktop\Certificado.cer'
      senha: O5KxP8QnwTspZz2YC5Dm8g==
      tipo-transmissor: '1'
      numero-transmissor: '11111111111'
    - codigo: '11111111'
      chave: 'C:\Users\Lenovo\Google Drive\instalador1.1.14.zip'
      senha: HYUZYbj+iqh/Ou3v4bsNrw==
      tipo-transmissor: '1'
      numero-transmissor: '11111111111'
    - codigo: '11111111'
      chave: 'C:\Users\Lenovo\Downloads\512x512.png.ico'
      senha: PyBH2cnmaGEjO3a04/WWbg==
      tipo-transmissor: '1'
      numero-transmissor: '11111111111'
    - codigo: '11111111'
      chave: 'C:\Users\Lenovo\Downloads\512x512.png.ico'
      senha: O5KxP8QnwTspZz2YC5Dm8g==
      tipo-transmissor: '1'
      numero-transmissor: '11111111111'
  consulta.governo: 0 */1 * * * *
  envio.governo: '*/30 * * * * * '
  s1000: '*/30 * * * * *'
