---
  server: 
    port: 5555
  spring: 
    activemq: 
      broker-url: "failover://(tcp://34.75.184.160:61616)?nested.wireFormat.maxInactivityDuration=0&nested.wireFormat.maxInactivityDurationInitalDelay=30000&warnAfterReconnectAttempts=5"
      user: "admin"
      password: "admin"
      in-memory: false
    profiles: 
      active: "IntegrationTest"
  db: 
    url: "jdbc:sqlserver://localhost:1433;databaseName=master"
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: "sa"
    password: "2kMlGjVPzuzuCR2MQh3Pkg=="
    datasource: 
      validation-query: "SELECT 1"
      type: "com.zaxxer.hikari.HikariDataSource"
      hikari: 
        poolName: "HikariPoolArkhi"
        connectionTimeout: 120000
        maximumPoolSize: 5
        minimumIdle: 1
        maxLifetime: 300000
  logging: 
    level: 
      com.arterh.esocial: "DEBUG"
      com.arkhi.esocial.util: "DEBUG"
      org.apache.activemq: "WARN"
      org.springframework.jdbc: "TRACE"
      com.zaxxer.hikari: "DEBUG"
    path: "./"
    pathArquivoMensagensDoSistema: "./src/main/resources/mensagens-mensageria.yml"
  servidorNTP: 
    url: "a.st1.ntp.br"
    maximoTentativasDeAcesso: 5
    intervaloEntreTentativasDeAcesso: 15000
  certificado: 
    servidor: 
      chave: "./src/test/resources/serpro.jks"
      senha: "5CjURCei2z5IcU1iAJNSJA=="
  serpro: 
    url_producao: 
      envio: "https://webservices.envio.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc"
      consulta: "https://webservices.consulta.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc"
    url_pre_producao: 
      envio: "https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/enviarloteeventos/WsEnviarLoteEventos.svc"
      consulta: "https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/consultarloteeventos/WsConsultarLoteEventos.svc"
  reinf: 
    ativo: true
    url_producao: 
      envio: "https://reinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc"
      consulta: "https://reinf.receita.fazenda.gov.br/WsREINF/ConsultasReinf.svc"
    url_pre_producao: 
      envio: "https://preprodefdreinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc"
      consulta: "https://preprodefdreinf.receita.fazenda.gov.br/WsREINF/ConsultasReinf.svc"
  esocial: 
    evento: 
      verificado: "V"
      naoprocessado: "L,Q,W,S"
      extraidoparaenvio: "X"
      recebidopelogoverno: "R"
      extraidoparaconsulta: "D"
      falhaInfraestrutura: "I"
      falhaDeXML: "E"
      finalizado: "C"
    tamanhoMaximoPacote: 750
    maximoEventosPorPacote: 2
    versaoLayoutProducao: "02_04_02,02_05_00"
    versaoLayoutPreProducao: "02_04_02,02_05_00"
    empregadores: 
      - 
        codigo: "23246515"
        chave: "./src/main/resources/ARTE INFORMATICA LTDA23246515000171NOVO.pfx"
        senha: "J9IixVpLNA4bC0nCuTHc4g=="
        tipo-transmissor: "1"
        numero-transmissor: "23246515000171"
      - 
        codigo: "05319244"
        chave: "./src/main/resources/ARTE INFORMATICA LTDA23246515000171NOVO.pfx"
        senha: "J9IixVpLNA4bC0nCuTHc4g=="
        tipo-transmissor: 1
        numero-transmissor: "05319244000171"
      - 
        codigo: "22151806"
        chave: "./src/main/resources/CertificadoCPFParaFinsDeTeste.pfx"
        senha: "5CjURCei2z5IcU1iAJNSJA=="
        tipo-transmissor: 2
        numero-transmissor: "22151806685"
    consulta.governo: "0 0 0 25 2 *"
    envio.governo: "0 0 0 25 2 *"
    atualizaInfoCertificados: "0 0 1 * * *"
    atualizaInfoLicencas: "0 0 1 * * *"
    s1000: "0 0 0 25 2 *"
